Todo List: add & remove
musangamfure/Todo-List-App pull request #2
Opened 2023-05-05 18:42 UTC by musangamfure

Hello,

In this PR, I have implement the remove, edit, sort and add features to the Todo List Project by using Vanilla JavaScipt, HTML and CSS.

**Here is what I followed:**

- Remove all hardcoded items from the tasks array.

- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task 
- Implement a function for deleting a task 
- Implement a function for editing task descriptions.
- All changes to the To-Do List are saved in local storage.

Kindly, Review my work and let me know what you think.

Best Regards.

2023-05-05 19:01 UTC, zainsadaqat requested changes
# Required Changes 🔁
## Hello  @musangamfure 👋 🙂

You're doing a great job on your project. We're proud of you. Good job so far! 

It's OK to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job. 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of GitHub Flow
  ✅  Descriptive Pull Request
  ✅  No linter errors

## Required Changes ♻️

- [ ] 

<img src="https://media0.giphy.com/media/HxnMNAEQgHqEHcGKBb/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 19:01 UTC, zainsadaqat commented on src/index.js
> +}
### [REQUIRED]

According to the requirement, the index should start from 1 For example if there are 5 tasks then the last index will be 5.

2023-05-05 20:04 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @musangamfure 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 20:04 UTC, anagudelogu commented on src/index.js
> +}
- [ ] You did a good job working on this milestone. 💯 However, the error that the previous reviewer pointed out still exists, the reason is that here in your `addTodo` function, you're initializing the index as the `todoItems` array length, which always starts as 0.  Please consider fixing this!

- [ ] I also noticed a new bug caused by the changes you introduced:

[Screencast from 05-05-23 14:57:11.webm](https://user-images.githubusercontent.com/77069011/236558109-d9f44adf-a66f-45ac-a037-38e4da3e54cf.webm)
 
This is because you modified some for loops to start in `i = 1` which causes the task at position 0 to be ignored. Please consider addressing this issue! 🤓 🔧

2023-05-06 00:12 UTC, binhussen approved these changes
Hi @musangamfure , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Implemented CRUD ✔️
- Used webpack ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 08:52 UTC, merged